add_traj: true
agent: our
bs: 12
epochs: 15
exp_id: rvt2_traj_example
num_workers: 3
peract:
  add_rgc_loss: true
  amp: true
  bnb: true
  lambda_weight_l2: 0.0001
  lr: 1.25e-05
  lr_cos_dec: true
  num_rotation_classes: 72
  optimizer_type: lamb
  transform_augmentation: true
  transform_augmentation_rpy:
  - 0.0
  - 0.0
  - 45.0
  transform_augmentation_xyz:
  - 0.125
  - 0.125
  - 0.125
  warmup_steps: 2000
peract_official:
  cfg_path: configs/peract_official_config.yaml
resume: ''
rlbench:
  cameras:
  - front
rvt:
  gt_hm_sigma: 1.5
  img_aug: 0.0
  move_pc_in_bound: true
  place_with_mean: false
sample_distribution_mode: task_uniform
tasks: light_bulb_in
train_iter: 160000
traj:
  lang_instruction_path: /home/nil/robotics/RVT/rvt/instructions.pkl
  trajectory_root_dir: /home/nil/robotics/RVT/rvt/data/train_traj

