exp_id: rvt2_traj_example
tasks: light_bulb_in
bs: 24
num_workers: 3
epochs: 15
sample_distribution_mode: task_uniform
peract:
  lr: 1.25e-5
  warmup_steps: 2000
  optimizer_type: lamb
  lr_cos_dec: True
  transform_augmentation_xyz: [0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0.0, 0.0, 45.0]
  amp: True
  bnb: True
  lambda_weight_l2: 1e-4
rvt:
  place_with_mean: False
  img_aug: 0.0

# use only front view
rlbench:
  cameras: 
        - front
        
# Adding Trajectory Configuration
add_traj: True
traj:
  trajectory_root_dir: /home/nil/robotics/RVT/rvt/data/train_traj # TODO: change this
  lang_instruction_path: /home/nil/robotics/RVT/rvt/instructions.pkl # TODO: change this

